"""add cancelled_at to cohorts table

Revision ID: 9b22f910f2c6
Revises: 
Create Date: 2025-11-11 14:08:46.702139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b22f910f2c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_cohorts_cancelled_at'), 'cohorts', ['cancelled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohorts_cancelled_at'), table_name='cohorts')
    op.drop_column('cohorts', 'cancelled_at')
    # ### end Alembic commands ###


